### ISSUE TITLE
Lost Connection to the Fitbit app

### ISSUE THREAD

**Issue by aolanig** [TimeToogo/spotify-hr#17]
I have a Fitbit Versa... and it says that it's still connecting so I left it for over 5 minutes and it's still not connecting. I have Bluetooth on, WIFI connected, Spotify on and opened, Fitbit app open, and I synced it multiple times to the Fitbit app, but still nothing. I need help because I don't know what to do anymore.

**Comment by Claremce** [comment]
I am having the same problem with my ionic. Would like to know how to fix and get Spotify working
Thank you

**Comment by DaiseyB** [comment]
I am having the same problem with my versa. I’ve trued everything including a factory reset of the device.

**Comment by Tjiam43** [comment]
Also getting the same error. I just found out that you need a Spotify premium account for this app to work, I only have a free account, I wonder if that's causing the issue. The developer should mention that in the app's description so other people don't waste their time installing this and trying to troubleshoot it.

**Comment by JULESTAY** [comment]
I am having issues with my Fitbit versa also. It keeps saying that I lost connection to the Fitbit app. I have the premium account so I want to know what I need to do to fix this so I don’t have this issue again. Thank you!

**Comment by lisawagner2003** [comment]
I am also having this problem and I have the premium Spotify account.  Was there a fix for this?

**Comment by TimeToogo** [comment]
This usually happens when the Spotify app cannot communicate with the FitBit app on your iOS/Android device.

Please ensure that:

- Bluetooth is enabled on your phone and the watch is connected via Bluetooth
- The FitBit app is running and has permission to run in the background

If it's still not working, please open the FitBit app on your phone and sync your FitBit by dragging down on the main screen.
